version: "3"

services:
    sourcecode:
        container_name: online-store-server
        restart: always
        build: ./source-code/
        ports:
            - "3000:3000"
        links:
            - mysql
        depends_on:
            - mysql
        env_file: .env.server
        networks:
            - online-store


    mysql:
        container_name: online_store_db
        image: mysql
        restart: always
        ports:
            - "8080:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./mysql-data:/var/lib/mysql
        networks:
            - online-store
networks:
    online-store:
        external: true
