version: "3"

services:
    mysqldb:
        container_name: online_store_db
        image: mysql
        restart: always
        ports:
            - "8080:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./mysql-data:/var/lib/mysql
        networks:
            - "online-store"

networks:
    online-store:
        external: true
