version: "3"

services:
    mysqldb:
        container_name: online_store_db
        image: mysql
        restart: always
        ports: 
            - "3306:3306"
        networks:
            - "online-store"
        volumes:
            - /opt/mysql_data:/var/lib/mysql

networks:
    online-store:
        external: true
